import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import SearchForm from '../components/SearchForm/SearchForm'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Is it accessible?</h1>
        <p>Check if that npm package you’re about to install has accessibility issues</p>
        <SearchForm />
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
